networks:
  dev:

volumes:
  pgdata: # Define the pgdata volume here

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://jate_satis:6Akshn21IKBO0622@db:5432/large_images_db"
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  db:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jate_satis
      POSTGRES_PASSWORD: 6Akshn21IKBO0622
      POSTGRES_DB: large_images_db
    ports:
      - "5432:5432"
    networks:
      - dev
